server:
  port: 8080
spring:
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jblog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    suffix: .html
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
  jackson:
    date-format: yyyy-MM  -dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/com/jyan/mapper/xml/*.xml